version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/fullstack/frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "pip"
    directory: "/fullstack/backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
