version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: persistent_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  haskell-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: haskell_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

  worker-task:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: haskell_worker
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
