"""add future

Revision ID: 09092ab0776f
Revises: 3e078aac4c14
Create Date: 2025-03-11 10:45:20.142427

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '09092ab0776f'
down_revision = '3e078aac4c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('apply_to_future', sa.Boolean(), nullable=True))
    op.execute("UPDATE audit_log SET apply_to_future = False")
    op.alter_column('audit_log', 'apply_to_future', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log', 'apply_to_future')
    # ### end Alembic commands ###
