"""add effect log

Revision ID: 0c685cc47947
Revises: c7869d69efcf
Create Date: 2025-04-22 00:00:26.340328

"""
from alembic import op
import alembic
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from app.alembic.helpers import apply_and_grant_rls


# revision identifiers, used by Alembic.
revision = '0c685cc47947'
down_revision = 'c7869d69efcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('effect_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('effect_type', sa.Enum('EMAIL', 'IN_APP', name='effecttype'), nullable=False),
    sa.Column('event_type', sa.Enum('NEW_TRANSACTION', 'NEW_ACCOUNT_LINKED', name='eventtype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    apply_and_grant_rls(op.get_bind())
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('effect_log')
    # ### end Alembic commands ###
