"""make an app user for db access

Revision ID: 0ddafe515a7a
Revises: 185da06ff595
Create Date: 2025-03-01 11:36:18.809483

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0ddafe515a7a'
down_revision = '185da06ff595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
