"""regex

Revision ID: 0e482d3745ce
Revises: 234d3ea9fbba
Create Date: 2025-02-15 09:50:57.375989

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0e482d3745ce'
down_revision = '234d3ea9fbba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload_configuration', 'filename_regex',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload_configuration', 'filename_regex',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
