"""add event type for budget

Revision ID: 1511806f774a
Revises: 34870736dd44
Create Date: 2025-06-05 16:00:59.193029

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from app.alembic.helpers import add_to_enum


# revision identifiers, used by Alembic.
revision = '1511806f774a'
down_revision = '34870736dd44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    add_to_enum(op.get_bind(), "eventtype", "budget_threshold_exceeded")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
