"""few more pos updates

Revision ID: 19f82cb176d1
Revises: d997bb0b4dc0
Create Date: 2025-05-20 09:34:54.473830

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '19f82cb176d1'
down_revision = 'd997bb0b4dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant_group', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('variant_group', sa.Column('order_of_appearance', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variant_group', 'order_of_appearance')
    op.drop_column('variant_group', 'active')
    op.drop_constraint(None, 'orderable', type_='foreignkey')
    op.drop_column('orderable', 'user_id')
    # ### end Alembic commands ###
