"""add nocode tables

Revision ID: 1b93ef41edb5
Revises: 58cc9851c43e
Create Date: 2025-04-26 17:01:31.161416

"""
from alembic import op
import sqlalchemy as sa

from app.alembic.helpers import apply_and_grant_rls


# revision identifiers, used by Alembic.
revision = '1b93ef41edb5'
down_revision = '58cc9851c43e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('no_code_canvas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('no_code_parameter_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_type', sa.Enum('GLOBAL', 'WIDGET', name='parametergrouptype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('canvas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['no_code_canvas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('no_code_widget',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('canvas_id', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('column', sa.Integer(), nullable=False),
    sa.Column('row_span', sa.Integer(), nullable=False),
    sa.Column('col_span', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['no_code_canvas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('no_code_parameter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('INT', 'FLOAT', 'STRING', 'SELECT', 'SUBMIT', 'DATETIME', 'PAGINATION', 'MULTI_SELECT', name='parametertype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('trigger_refetch', sa.Boolean(), nullable=False),
    sa.Column('dependent_widgets', sa.JSON(), nullable=False),
    sa.Column('option_source_type', sa.Enum('STATIC', 'DYNAMIC', name='parameteroptionsourcetype'), nullable=True),
    sa.Column('option_generator_key', sa.String(), nullable=True),
    sa.Column('default_value', sa.JSON(), nullable=True),
    sa.Column('display_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['no_code_parameter_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('no_code_tool',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('widget_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('canvas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['no_code_canvas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['widget_id'], ['no_code_widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('no_code_parameter_option',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parameter_id'], ['no_code_parameter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('no_code_pipeline_step',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('widget_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['no_code_tool.id'], ),
    sa.ForeignKeyConstraint(['widget_id'], ['no_code_widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    conn = op.get_bind()
    apply_and_grant_rls(conn)
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('no_code_pipeline_step')
    op.drop_table('no_code_parameter_option')
    op.drop_table('no_code_tool')
    op.drop_table('no_code_parameter')
    op.drop_table('no_code_widget')
    op.drop_table('no_code_parameter_group')
    op.drop_table('no_code_canvas')
    # ### end Alembic commands ###
