"""misc

Revision ID: 1ba55989225a
Revises: a92bf6197b96
Create Date: 2025-05-20 21:31:23.272932

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from app.alembic.helpers import apply_and_grant_rls


# revision identifiers, used by Alembic.
revision = '1ba55989225a'
down_revision = 'a92bf6197b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    apply_and_grant_rls(op.get_bind())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
