"""datetime

Revision ID: 234d3ea9fbba
Revises: f0d65c06dc63
Create Date: 2025-02-14 20:31:40.367573

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '234d3ea9fbba'
down_revision = 'f0d65c06dc63'
branch_labels = None
depends_on = None


def upgrade():
    # Alter column with explicit USING clause for conversion
    op.execute("""
        ALTER TABLE uploaded_pdf 
        ALTER COLUMN upload_time 
        TYPE TIMESTAMP WITHOUT TIME ZONE 
        USING upload_time::timestamp without time zone;
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uploaded_pdf', 'upload_time',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
