"""add ref name

Revision ID: 2e762bbd17d5
Revises: 671dbf271aa0
Create Date: 2025-06-04 18:02:21.882185

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2e762bbd17d5'
down_revision = '671dbf271aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('effect', sa.Column('ref_name', sa.String(), nullable=True))
    op.execute("UPDATE effect SET ref_name = id::TEXT")
    op.alter_column('effect', 'ref_name', nullable=False)
    op.create_index("ix_effect_ref_name", "effect", ["ref_name"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_effect_ref_name", table_name="effect")
    op.drop_column('effect', 'ref_name')
    # ### end Alembic commands ###
