"""update conditional enum

Revision ID: 34870736dd44
Revises: 2e762bbd17d5
Create Date: 2025-06-04 18:19:39.339233

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from app.models.effect import EffectConditionals
from app.alembic.helpers import add_to_enum


# revision identifiers, used by Alembic.
revision = '34870736dd44'
down_revision = '2e762bbd17d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_effect_ref_name', table_name='effect')
    op.create_unique_constraint('ix_effect_user_id_ref_name', 'effect', ['user_id', 'ref_name'])
    add_to_enum(op, "effectconditionals", "UNCONDITIONAL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ix_effect_user_id_ref_name", 'effect', type_='unique')
    op.create_index('ix_effect_ref_name', 'effect', ['ref_name'], unique=True)
    # ### end Alembic commands ###
