"""add back cron state

Revision ID: 3a6101ac7c2a
Revises: fe00d439cb07
Create Date: 2025-06-13 09:13:26.182071

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3a6101ac7c2a'
down_revision = 'fe00d439cb07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_state',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('job_name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('last_run', sa.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='cron_state_pkey'),
        sa.UniqueConstraint('job_name', name='cron_state_job_name_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cron_state')
    # ### end Alembic commands ###
