"""add shops

Revision ID: 41e0c2917330
Revises: d48f6eb59b8d
Create Date: 2025-06-04 12:08:35.632936

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '41e0c2917330'
down_revision = 'd48f6eb59b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_orderer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order', sa.Column('placed_by', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('pickup_time', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'order', 'guest_orderer', ['placed_by'], ['id'])
    op.create_foreign_key(None, 'order', 'shop', ['shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'pickup_time')
    op.drop_column('order', 'shop_id')
    op.drop_column('order', 'placed_by')
    op.drop_table('shop')
    op.drop_table('guest_orderer')
    # ### end Alembic commands ###
