"""add tfa

Revision ID: 43943e6e807d
Revises: 72bfa90cbf7d
Create Date: 2025-04-05 08:58:10.041062

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '43943e6e807d'
down_revision = '72bfa90cbf7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('totp_secret', sa.String(), nullable=True))
    op.add_column('user', sa.Column('totp_enabled', sa.Boolean(), nullable=True))
    op.execute('UPDATE "user" SET totp_enabled = FALSE')
    op.alter_column('user', 'totp_enabled', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'totp_enabled')
    op.drop_column('user', 'totp_secret')
    # ### end Alembic commands ###
