"""cursor added

Revision ID: 525c2b139771
Revises: f7a9786bb731
Create Date: 2025-03-24 10:56:38.453738

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '525c2b139771'
down_revision = 'f7a9786bb731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plaid_account', sa.Column('cursor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plaid_account', 'cursor')
    # ### end Alembic commands ###
