"""unique on slug=user

Revision ID: 53da2b95fcd2
Revises: 1b93ef41edb5
Create Date: 2025-04-26 17:25:51.055966

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '53da2b95fcd2'
down_revision = '1b93ef41edb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_slug', 'no_code_canvas', ['user_id', 'slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_slug', 'no_code_canvas', type_='unique')
    # ### end Alembic commands ###
