"""remove is public

Revision ID: 55037c2f45fd
Revises: 4c80b372ac65
Create Date: 2025-04-02 18:09:52.731550

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '55037c2f45fd'
down_revision = '4c80b372ac65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_filter', 'is_public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_filter', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
