"""add widget_type

Revision ID: 589ada5d1a44
Revises: 53da2b95fcd2
Create Date: 2025-04-26 17:34:29.179006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '589ada5d1a44'
down_revision = '53da2b95fcd2'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Create the ENUM type
    widget_type_enum = postgresql.ENUM(
        'value', 'value_with_trend', 'badge', 'list', 'pie_chart', 'bar_chart', 'separator', 'form',
        name='widgettype'
    )
    widget_type_enum.create(op.get_bind())

    # 2. Then add the column
    op.add_column('no_code_widget', sa.Column('widget_type', widget_type_enum, nullable=True))



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('no_code_widget', 'widget_type')
    # ### end Alembic commands ###
