"""update to be generic balance

Revision ID: 58cc9851c43e
Revises: e4ee5cb8850d
Create Date: 2025-04-24 22:08:14.682268

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '58cc9851c43e'
down_revision = 'e4ee5cb8850d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plaid_account_balance', sa.Column('transaction_source_id', sa.Integer(), nullable=True))
    op.alter_column('plaid_account_balance', 'plaid_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_plaid_account_balance_transaction_source_id'), 'plaid_account_balance', ['transaction_source_id'], unique=False)
    op.create_foreign_key(None, 'plaid_account_balance', 'transaction_source', ['transaction_source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plaid_account_balance', type_='foreignkey')
    op.drop_index(op.f('ix_plaid_account_balance_transaction_source_id'), table_name='plaid_account_balance')
    op.alter_column('plaid_account_balance', 'plaid_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('plaid_account_balance', 'transaction_source_id')
    # ### end Alembic commands ###
