"""active effects;


Revision ID: 671dbf271aa0
Revises: 41e0c2917330
Create Date: 2025-06-04 13:59:18.822967

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '671dbf271aa0'
down_revision = '41e0c2917330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('effect', sa.Column('active', sa.Boolean(), nullable=True))
    # set all active to true
    op.execute("UPDATE effect SET active = true")
    op.alter_column('effect', 'active', nullable=False)
    
    op.add_column('effect', sa.Column('editable', sa.Boolean(), nullable=True))
    # set all editable to true
    op.execute("UPDATE effect SET editable = false")
    op.alter_column('effect', 'editable', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('effect', 'editable')
    op.drop_column('effect', 'active')
    # ### end Alembic commands ###
