"""require 2fa

Revision ID: 72bfa90cbf7d
Revises: 55037c2f45fd
Create Date: 2025-04-04 11:03:29.021818

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '72bfa90cbf7d'
down_revision = '55037c2f45fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('requires_two_factor', sa.Boolean(), nullable=True))
    op.execute('UPDATE "user" SET requires_two_factor = FALSE')
    op.alter_column('user', 'requires_two_factor', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'requires_two_factor')
    # ### end Alembic commands ###
