"""plaid make pdf id nullable

Revision ID: 7463c25d205d
Revises: db97df562cb6
Create Date: 2025-04-02 09:52:24.059485

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7463c25d205d'
down_revision = 'db97df562cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('process_file_job', 'pdf_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('process_file_job', 'pdf_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
