"""add effects table

Revision ID: 7851136dc921
Revises: 0c685cc47947
Create Date: 2025-04-22 22:22:00.708121

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from app.alembic.helpers import apply_and_grant_rls


# revision identifiers, used by Alembic.
revision = '7851136dc921'
down_revision = '0c685cc47947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('effect',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=False),
    sa.Column('template', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('condition', sa.Enum('AMOUNT_OVER', 'COUNT_OF_TRANSACTIONS', name='effectconditionals'), nullable=False),
    sa.Column('conditional_parameters', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # this is required to use the existing enum
    op.add_column(
        'effect',
        sa.Column('effect_type', sa.Enum(name='effecttype'), nullable=False),
    )
    op.add_column(
        'effect',
    sa.Column('event_type', sa.Enum(name='eventtype'), nullable=False),
    )
    connection = op.get_bind()
    apply_and_grant_rls(connection)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('effect')
    # ### end Alembic commands ###
