"""update models for budgets

Revision ID: 78fd9ce5e29d
Revises: 31adec2c693f
Create Date: 2025-03-04 07:19:04.789185

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '78fd9ce5e29d'
down_revision = '31adec2c693f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_category_link', sa.Column('budget_entry_id', sa.Integer(), nullable=False))
    op.drop_constraint('budget_category_link_budget_id_fkey', 'budget_category_link', type_='foreignkey')
    op.create_foreign_key(None, 'budget_category_link', 'budget_entry', ['budget_entry_id'], ['id'])
    op.drop_column('budget_category_link', 'budget_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_category_link', sa.Column('budget_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'budget_category_link', type_='foreignkey')
    op.create_foreign_key('budget_category_link_budget_id_fkey', 'budget_category_link', 'budget', ['budget_id'], ['id'])
    op.drop_column('budget_category_link', 'budget_entry_id')
    # ### end Alembic commands ###
