"""send emails

Revision ID: 820236a2036c
Revises: 09092ab0776f
Create Date: 2025-03-14 14:06:17.937321

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '820236a2036c'
down_revision = '09092ab0776f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('send_email', sa.Boolean(), nullable=True))
    op.execute('UPDATE "user" SET send_email = true')  
    op.alter_column('user', 'send_email', nullable=False) 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'send_email')
    # ### end Alembic commands ###
