"""add worker status

Revision ID: 835cbe099932
Revises: 43943e6e807d
Create Date: 2025-04-11 19:25:06.703846

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '835cbe099932'
down_revision = '43943e6e807d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'preparing_for_parse', 'fetching_transactions', 'parsing_transactions', 'categorizing_transactions', 'failed', 'completed', name='processingstate'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('additional_info', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_status')
    # ### end Alembic commands ###
