"""add widget_type not null

Revision ID: 86487e36e053
Revises: 589ada5d1a44
Create Date: 2025-04-26 17:38:28.116643

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '86487e36e053'
down_revision = '589ada5d1a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('no_code_widget', 'widget_type',
               existing_type=postgresql.ENUM('value', 'value_with_trend', 'badge', 'list', 'pie_chart', 'bar_chart', 'separator', 'form', name='widgettype'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('no_code_widget', 'widget_type',
               existing_type=postgresql.ENUM('value', 'value_with_trend', 'badge', 'list', 'pie_chart', 'bar_chart', 'separator', 'form', name='widgettype'),
               nullable=True)
    # ### end Alembic commands ###
