"""add nickname

Revision ID: 878e38c33467
Revises: 185da06ff595
Create Date: 2025-03-01 18:04:51.138676

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '878e38c33467'
down_revision = '185da06ff595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_pdf', sa.Column('nickname', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_pdf', 'nickname')
    # ### end Alembic commands ###
