"""add plaid balance

Revision ID: 976d7e5b6aca
Revises: f1f7c192b807
Create Date: 2025-04-19 00:36:48.552708

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from fullstack.backend.app.alembic import helpers


# revision identifiers, used by Alembic.
revision = '976d7e5b6aca'
down_revision = 'f1f7c192b807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_account_balance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plaid_account_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plaid_account_id'], ['plaid_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plaid_account_balance_plaid_account_id'), 'plaid_account_balance', ['plaid_account_id'], unique=False)
    connection = op.get_bind()
    helpers.apply_and_grant_rls(connection)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plaid_account_balance_plaid_account_id'), table_name='plaid_account_balance')
    op.drop_table('plaid_account_balance')
    # ### end Alembic commands ###
