"""rename budget column

Revision ID: a157b579a21e
Revises: dc9f19b1aaf0
Create Date: 2025-06-06 17:26:09.923281

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a157b579a21e'
down_revision = 'dc9f19b1aaf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget_entry', 'amount', new_column_name='monthly_target')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget_entry', 'monthly_target', new_column_name='amount')
    # ### end Alembic commands ###
