"""add active

Revision ID: a912abebfabb
Revises: 6379edd780cb
Create Date: 2025-05-30 11:48:03.132998

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a912abebfabb'
down_revision = '6379edd780cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plaid_account', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plaid_account', 'active')
    # ### end Alembic commands ###
