"""apply rls

Revision ID: a92bf6197b96
Revises: f73f7a29e327
Create Date: 2025-05-20 19:56:43.129302

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from app.alembic.helpers import apply_and_grant_rls

# revision identifiers, used by Alembic.
revision = 'a92bf6197b96'
down_revision = 'f73f7a29e327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    apply_and_grant_rls(op.get_bind())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
