"""erros

Revision ID: aaa0e5ffa328
Revises: 0e482d3745ce
Create Date: 2025-02-15 09:54:07.915606

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'aaa0e5ffa328'
down_revision = '0e482d3745ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_file_job', sa.Column('error_messages', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process_file_job', 'error_messages')
    # ### end Alembic commands ###
