"""update balance

Revision ID: c7869d69efcf
Revises: 976d7e5b6aca
Create Date: 2025-04-19 14:30:27.801709

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c7869d69efcf'
down_revision = '976d7e5b6aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plaid_account_balance', sa.Column('available', sa.Float(), nullable=True))
    op.add_column('plaid_account_balance', sa.Column('iso_currency_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plaid_account_balance', 'iso_currency_code')
    op.drop_column('plaid_account_balance', 'available')
    # ### end Alembic commands ###
