"""optional transaction_id

Revision ID: d48f6eb59b8d
Revises: fdeacf5af3ce
Create Date: 2025-06-03 09:20:09.482737

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd48f6eb59b8d'
down_revision = 'fdeacf5af3ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
