"""archived not active

Revision ID: d6a4cd6e4dc3
Revises: a157b579a21e
Create Date: 2025-06-07 09:16:03.097968

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd6a4cd6e4dc3'
down_revision = 'a157b579a21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plaid_account', sa.Column('archived', sa.Boolean(), nullable=True))
    op.execute("UPDATE plaid_account SET archived = NOT active OR True")
    op.alter_column('plaid_account', 'archived', nullable=False)
    op.drop_column('plaid_account', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plaid_account', 'archived')
    # ### end Alembic commands ###
