"""apply rls

Revision ID: d997bb0b4dc0
Revises: 22b3ce55c90f
Create Date: 2025-05-20 08:19:56.629041

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from app.alembic.helpers import apply_and_grant_rls


# revision identifiers, used by Alembic.
revision = 'd997bb0b4dc0'
down_revision = '22b3ce55c90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    apply_and_grant_rls(op.get_bind())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
