"""plaid recat

Revision ID: db97df562cb6
Revises: 563debaa5cf6
Create Date: 2025-04-02 09:30:21.362996

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'db97df562cb6'
down_revision = '563debaa5cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE jobkind ADD VALUE IF NOT EXISTS 'plaid_recategorize'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Cannot easily remove enum values in PostgreSQL, so we'll leave it for downgrade
    # If needed, you would need to create a new enum without the value and migrate data
    pass
    # ### end Alembic commands ###
