"""fix_enum

Revision ID: dc9f19b1aaf0
Revises: 1511806f774a
Create Date: 2025-06-05 16:41:43.857624

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from app.alembic.helpers import add_to_enum


# revision identifiers, used by Alembic.
revision = 'dc9f19b1aaf0'
down_revision = '1511806f774a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    add_to_enum(op.get_bind(), "eventtype", "BUDGET_THRESHOLD_EXCEEDED")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
