"""remove unneeded fk

Revision ID: e49be03aec16
Revises: fcea2e92e0cd
Create Date: 2025-02-24 22:35:52.504177

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e49be03aec16'
down_revision = 'fcea2e92e0cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sankey_linkage_source_id_fkey', 'sankey_linkage', type_='foreignkey')
    op.drop_column('sankey_linkage', 'source_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sankey_linkage', sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('sankey_linkage_source_id_fkey', 'sankey_linkage', 'transaction_source', ['source_id'], ['id'])
    # ### end Alembic commands ###
