"""tool param join table

Revision ID: e4bd371e21de
Revises: 86487e36e053
Create Date: 2025-04-26 18:04:53.023288

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from app.alembic.helpers import apply_and_grant_rls


# revision identifiers, used by Alembic.
revision = 'e4bd371e21de'
down_revision = '86487e36e053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('no_code_tool_parameter',
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parameter_id'], ['no_code_parameter.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['no_code_tool.id'], ),
    sa.PrimaryKeyConstraint('tool_id', 'parameter_id')
    )

    conn = op.get_bind()
    apply_and_grant_rls(conn)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('no_code_tool_parameter')
    # ### end Alembic commands ###
