"""add last active at time

Revision ID: e4ee5cb8850d
Revises: 9e1695f27650
Create Date: 2025-04-24 10:31:42.653259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ee5cb8850d'
down_revision = '9e1695f27650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_visited_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_visited_at')
    # ### end Alembic commands ###
