"""settings

Revision ID: f1ee96438af4
Revises: 820236a2036c
Create Date: 2025-03-16 20:33:51.432112

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f1ee96438af4'
down_revision = '820236a2036c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('settings', sa.JSON(), nullable=True))
    op.execute("UPDATE \"user\" SET settings = '{\"has_budget\": false, \"power_user_filters\": true}'")
    op.alter_column('user', 'settings', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'settings')
    # ### end Alembic commands ###
