"""add join table on variants

Revision ID: f73f7a29e327
Revises: c6e080af195a
Create Date: 2025-05-20 19:56:08.241349

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f73f7a29e327'
down_revision = 'c6e080af195a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variant_group_orderable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('variant_group_id', sa.Integer(), nullable=False),
    sa.Column('orderable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orderable_id'], ['orderable.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['variant_group_id'], ['variant_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('variant_group', 'orderable_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant_group', sa.Column('orderable_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('variant_group_orderable')
    # ### end Alembic commands ###
