"""add sync to plaid

Revision ID: f7a9786bb731
Revises: 9f629b41cb10
Create Date: 2025-03-23 07:30:12.885372

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f7a9786bb731'
down_revision = '9f629b41cb10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_sync_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plaid_item_id', sa.Integer(), nullable=False),
    sa.Column('plaid_account_id', sa.Integer(), nullable=True),
    sa.Column('sync_type', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('added_count', sa.Integer(), nullable=True),
    sa.Column('modified_count', sa.Integer(), nullable=True),
    sa.Column('removed_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plaid_account_id'], ['plaid_account.id'], ),
    sa.ForeignKeyConstraint(['plaid_item_id'], ['plaid_item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transaction', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('transaction', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_transaction_external_id'), 'transaction', ['external_id'], unique=False)
    connection = op.get_bind()
    for table_name in ["plaid_sync_log"]:
        connection.execute(sa.text(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY;"))
        connection.execute(sa.text(f"""
            CREATE POLICY user_isolation_policy ON {table_name}
            USING (user_id = current_setting('app.current_user_id')::int);
        """))
        print(f"✔ RLS applied to {table_name}")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_external_id'), table_name='transaction')
    op.drop_column('transaction', 'last_updated')
    op.drop_column('transaction', 'external_id')
    op.drop_table('plaid_sync_log')
    # ### end Alembic commands ###
