"""inputs and linkages

Revision ID: fcea2e92e0cd
Revises: a7e463792cb2
Create Date: 2025-02-22 19:08:26.296368

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fcea2e92e0cd'
down_revision = 'a7e463792cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sankey_input',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['config_id'], ['sankey_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sankey_linkage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('target_source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['config_id'], ['sankey_config.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['transaction_source.id'], ),
    sa.ForeignKeyConstraint(['target_source_id'], ['transaction_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sankey_linkage')
    op.drop_table('sankey_input')
    # ### end Alembic commands ###
