"""add to enum

Revision ID: fdeacf5af3ce
Revises: 65017d77a707
Create Date: 2025-06-02 13:59:42.786157

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from app.alembic.helpers import add_to_enum


# revision identifiers, used by Alembic.
revision = 'fdeacf5af3ce'
down_revision = '65017d77a707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    add_to_enum(op.get_bind(), "eventtype", "ACCOUNT_DEACTIVATED")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
