"""add widget_Type

Revision ID: fe00d439cb07
Revises: 712d66dbde72
Create Date: 2025-06-12 16:00:12.464620

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from app.alembic.helpers import add_to_enum

# revision identifiers, used by Alembic.
revision = 'fe00d439cb07'
down_revision = '712d66dbde72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cron_state')
    add_to_enum(op.get_bind(), "widgettype", "transaction_cards")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_run', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='cron_state_pkey'),
    sa.UniqueConstraint('job_name', name='cron_state_job_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
