version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: persistent_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  haskell-app:
    image: 067448242226.dkr.ecr.us-east-2.amazonaws.com/finance/app:latest
    container_name: haskell_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATABASE_URL: ${DATABASE_URL}

  worker-task:
    image: 067448242226.dkr.ecr.us-east-2.amazonaws.com/finance/worker:latest
    container_name: haskell_worker
    depends_on:
      - postgres
      - haskell-app
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATABASE_URL: ${DATABASE_URL}

volumes:
  postgres_data: