/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutTermsImport } from './routes/_layout/terms'
import { Route as LayoutSignupImport } from './routes/_layout/signup'
import { Route as LayoutResetPasswordImport } from './routes/_layout/reset-password'
import { Route as LayoutRecoverPasswordImport } from './routes/_layout/recover-password'
import { Route as LayoutPrivacyImport } from './routes/_layout/privacy'
import { Route as LayoutOldImport } from './routes/_layout/old'
import { Route as LayoutLoginImport } from './routes/_layout/login'
import { Route as LayoutLandingImport } from './routes/_layout/landing'
import { Route as LayoutHowImport } from './routes/_layout/how'
import { Route as LayoutFaqImport } from './routes/_layout/faq'
import { Route as LayoutDemoImport } from './routes/_layout/demo'
import { Route as LayoutContactMeImport } from './routes/_layout/contact-me'
import { Route as LayoutLoggedinImport } from './routes/_layout/_logged_in'
import { Route as LayoutLoggedinUploadFilesImport } from './routes/_layout/_logged_in/upload-files'
import { Route as LayoutLoggedinTransactionsImport } from './routes/_layout/_logged_in/transactions'
import { Route as LayoutLoggedinSettingsImport } from './routes/_layout/_logged_in/settings'
import { Route as LayoutLoggedinSankeyConfigImport } from './routes/_layout/_logged_in/sankey-config'
import { Route as LayoutLoggedinPlaidImport } from './routes/_layout/_logged_in/plaid'
import { Route as LayoutLoggedinManageAccountsImport } from './routes/_layout/_logged_in/manage-accounts'
import { Route as LayoutLoggedinBudgetImport } from './routes/_layout/_logged_in/budget'
import { Route as LayoutLoggedinAdminImport } from './routes/_layout/_logged_in/admin'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTermsRoute = LayoutTermsImport.update({
  path: '/terms',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSignupRoute = LayoutSignupImport.update({
  path: '/signup',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutResetPasswordRoute = LayoutResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutRecoverPasswordRoute = LayoutRecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPrivacyRoute = LayoutPrivacyImport.update({
  path: '/privacy',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutOldRoute = LayoutOldImport.update({
  path: '/old',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLoginRoute = LayoutLoginImport.update({
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLandingRoute = LayoutLandingImport.update({
  path: '/landing',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutHowRoute = LayoutHowImport.update({
  path: '/how',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutFaqRoute = LayoutFaqImport.update({
  path: '/faq',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDemoRoute = LayoutDemoImport.update({
  path: '/demo',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutContactMeRoute = LayoutContactMeImport.update({
  path: '/contact-me',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLoggedinRoute = LayoutLoggedinImport.update({
  id: '/_logged_in',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLoggedinUploadFilesRoute = LayoutLoggedinUploadFilesImport.update({
  path: '/upload-files',
  getParentRoute: () => LayoutLoggedinRoute,
} as any)

const LayoutLoggedinTransactionsRoute = LayoutLoggedinTransactionsImport.update(
  {
    path: '/transactions',
    getParentRoute: () => LayoutLoggedinRoute,
  } as any,
)

const LayoutLoggedinSettingsRoute = LayoutLoggedinSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutLoggedinRoute,
} as any)

const LayoutLoggedinSankeyConfigRoute = LayoutLoggedinSankeyConfigImport.update(
  {
    path: '/sankey-config',
    getParentRoute: () => LayoutLoggedinRoute,
  } as any,
)

const LayoutLoggedinPlaidRoute = LayoutLoggedinPlaidImport.update({
  path: '/plaid',
  getParentRoute: () => LayoutLoggedinRoute,
} as any)

const LayoutLoggedinManageAccountsRoute =
  LayoutLoggedinManageAccountsImport.update({
    path: '/manage-accounts',
    getParentRoute: () => LayoutLoggedinRoute,
  } as any)

const LayoutLoggedinBudgetRoute = LayoutLoggedinBudgetImport.update({
  path: '/budget',
  getParentRoute: () => LayoutLoggedinRoute,
} as any)

const LayoutLoggedinAdminRoute = LayoutLoggedinAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutLoggedinRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_logged_in': {
      preLoaderRoute: typeof LayoutLoggedinImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/contact-me': {
      preLoaderRoute: typeof LayoutContactMeImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/demo': {
      preLoaderRoute: typeof LayoutDemoImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/faq': {
      preLoaderRoute: typeof LayoutFaqImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/how': {
      preLoaderRoute: typeof LayoutHowImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/landing': {
      preLoaderRoute: typeof LayoutLandingImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/login': {
      preLoaderRoute: typeof LayoutLoginImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/old': {
      preLoaderRoute: typeof LayoutOldImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/privacy': {
      preLoaderRoute: typeof LayoutPrivacyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/recover-password': {
      preLoaderRoute: typeof LayoutRecoverPasswordImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/reset-password': {
      preLoaderRoute: typeof LayoutResetPasswordImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/signup': {
      preLoaderRoute: typeof LayoutSignupImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/terms': {
      preLoaderRoute: typeof LayoutTermsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_logged_in/admin': {
      preLoaderRoute: typeof LayoutLoggedinAdminImport
      parentRoute: typeof LayoutLoggedinImport
    }
    '/_layout/_logged_in/budget': {
      preLoaderRoute: typeof LayoutLoggedinBudgetImport
      parentRoute: typeof LayoutLoggedinImport
    }
    '/_layout/_logged_in/manage-accounts': {
      preLoaderRoute: typeof LayoutLoggedinManageAccountsImport
      parentRoute: typeof LayoutLoggedinImport
    }
    '/_layout/_logged_in/plaid': {
      preLoaderRoute: typeof LayoutLoggedinPlaidImport
      parentRoute: typeof LayoutLoggedinImport
    }
    '/_layout/_logged_in/sankey-config': {
      preLoaderRoute: typeof LayoutLoggedinSankeyConfigImport
      parentRoute: typeof LayoutLoggedinImport
    }
    '/_layout/_logged_in/settings': {
      preLoaderRoute: typeof LayoutLoggedinSettingsImport
      parentRoute: typeof LayoutLoggedinImport
    }
    '/_layout/_logged_in/transactions': {
      preLoaderRoute: typeof LayoutLoggedinTransactionsImport
      parentRoute: typeof LayoutLoggedinImport
    }
    '/_layout/_logged_in/upload-files': {
      preLoaderRoute: typeof LayoutLoggedinUploadFilesImport
      parentRoute: typeof LayoutLoggedinImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutLoggedinRoute.addChildren([
      LayoutLoggedinAdminRoute,
      LayoutLoggedinBudgetRoute,
      LayoutLoggedinManageAccountsRoute,
      LayoutLoggedinPlaidRoute,
      LayoutLoggedinSankeyConfigRoute,
      LayoutLoggedinSettingsRoute,
      LayoutLoggedinTransactionsRoute,
      LayoutLoggedinUploadFilesRoute,
    ]),
    LayoutContactMeRoute,
    LayoutDemoRoute,
    LayoutFaqRoute,
    LayoutHowRoute,
    LayoutLandingRoute,
    LayoutLoginRoute,
    LayoutOldRoute,
    LayoutPrivacyRoute,
    LayoutRecoverPasswordRoute,
    LayoutResetPasswordRoute,
    LayoutSignupRoute,
    LayoutTermsRoute,
    LayoutIndexRoute,
  ]),
])

/* prettier-ignore-end */
