name: deploy-branch
run-name: "Branch deploy #${{ github.run_number }} on PR ${{ github.event.number }}"
on: [ pull_request ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.FINANCE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        # echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
        # ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '
        echo "Current directory: $(pwd)"
        echo "Listing home directory:"
        if [ -v "$PRIVATE_KEY" ]; then echo "private key is set"; else echo "private key is not set"; fi
        echo "$HOST"
        echo "$USER"
        ls -la ~