name: Populate env file
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
permissions:
  id-token: write
  contents: read 
jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: setup AWS creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-skip-session-tagging: true
        aws-region: us-east-2
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
    - name: Grab Secrets
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        # get all secrets for the myFinance app.. a little brittle but makes adding new secrets easy
        secret-ids: |
          myFinance/*
        name-transformation: uppercase
        parse-json-secrets: false
    - name: populate template file
      uses: edgardleal/mustache-template-action@v1.0.0
      env:
        DOMAIN: dev
      with:
        input: templates/.env.template
        output: .env.${{ env.DOMAIN }}
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: .env.dev
        path: .env.dev
